### ISSUE TITLE
php artisan p:make:client {email} --admin is failing with error

### ISSUE THREAD

**Issue by ftsiadimos** [pterobilling/pterobilling#123]
**PteroBilling version**: [e.g. v0.1.0-alpha]

**Describe the bug**
Fresh installation is failing when I am trying to create the admin.  I tried to install it in a different server and in the same server with the Panel same resutls.
php artisan p:make:client {email} --admin

**To Reproduce**
Please follow the steps of the doc https://docs.pterobilling.org/docs/start/install

**Expected behavior**
Finish the installation.

**Screenshots**
![image](https://user-images.githubusercontent.com/11952266/129458049-d7dea2de-cccc-4c6f-ae4c-3adcd5f7599a.png)

**Server Information (please complete the following information):**
 - OS:  Centos8
 - Pterodactyl panel: 1.5.1.
 - Web server: nginx version: nginx/1.14.1
 - Database server: 10.3.28-1
 - PHP: 8.0
 - Redis server: redis-5.0.3-2

**Additional context**

**Comment by Bricklou** [comment]
You're following the documentation, which is ahead of the source code state. The doc specify instructions for the `unstable` branch.

You can test pterobilling with the demo website at: https://demo.pterobilling.org/
Otherwise, on this version there is a default user with thoses IDs: `admin@example.com`/`password`

**Comment by ftsiadimos** [comment]
What is the best way to finish the installation and try the product?

**Comment by Bricklou** [comment]
I really recommend you to try through the demo. The project is still in Alpha stage and a lot of features are missing.
If you're not already on the discord server, you can join us here: https://discord.gg/GQ5EWQz6MQ

**Comment by ftsiadimos** [comment]
I can't login to the demo...
If I buy the product how I am  going to install it?

**Comment by Bricklou** [comment]
You don't have to buy anything, it's an opensource project, it's free to use.
And about the demo website, looks like someone change IDs, I will reset the database, don't worry.

**Comment by ftsiadimos** [comment]
Can I install it in Debian? Or the product is under development and not working at the moment?

**Comment by ftsiadimos** [comment]
Sorry I was confused with the pterobill and pterobilling was the same thing.

**Comment by Bricklou** [comment]
> Can I install it in Debian? Or the product is under development and not working at the moment?
Yes you can, but as I said, you won't be able to make anything with it since it's still in alpha stage.
If you want a preview of what is done at the moment, just look at the demo website.



> Sorry I was confused with the pterobill and pterobilling was the same thing.
It's pterobilling, pterobill is completly something else.
Ptero**billing** is free and opensource panel, it uses a Laravel as project base
Ptero**bill** is a paid service using WHMCS to run.

They are totally different.
